from .a import *
from .b import *
from .c import *
from .d import *
from .e import *
from .f import *
from .g import *
from .h import *
from .i import *
from .j import *
from .k import *
from .l import *
from .m import *
from .n import *
from .o import *
from .p import *
from .q import *
from .r import *
from .s import *
from .t import *
from .u import *
from .v import *
from .w import *
from .x import *
from .y import *
from .z import *
from .num0 import *
from .num1 import *
from .num2 import *
from .num3 import *
from .num4 import *
from .num5 import *
from .num6 import *
from .num7 import *
from .num8 import *
from .num9 import *
from .dot import *
from .text import *
from .color import *
from .box import *
from .change_color import *
from .lsd import *
from .stop_a import *
from .next import *
from .clear import *
